Remove shebang from debug_set_command.sh in wpdocker; streamline function definition

diff --git a/src/shared/scripts/cli/bashly/wpdocker b/src/shared/scripts/cli/bashly/wpdocker
--- a/src/shared/scripts/cli/bashly/wpdocker
+++ b/src/shared/scripts/cli/bashly/wpdocker
@@ -2424,8 +2424,6 @@ wpdocker_nginx_reload_command() {
 wpdocker_debug_set_command() {
 
   # src/debug_set_command.sh
-  #!/bin/bash
-
   # Check if required variables are set
   if [[ -z "${args[action]}" || -z "$WPDOCKER_CONFIG_FILE" ]]; then
       echo "Error: Missing required arguments or configuration file."
@@ -2440,27 +2438,28 @@ wpdocker_debug_set_command() {
 
   # Perform action based on ${args[action]}
   case "${args[action]}" in
-      enable)
-          if grep -q 'DEBUG_MODE="true"' "$WPDOCKER_CONFIG_FILE"; then
-              echo "DEBUG_MODE is already enabled."
-          else
-              sed -i '' 's/DEBUG_MODE="false"/DEBUG_MODE="true"/' "$WPDOCKER_CONFIG_FILE"
-              echo "DEBUG_MODE has been enabled."
-          fi
-          ;;
-      disable)
-          if grep -q 'DEBUG_MODE="false"' "$WPDOCKER_CONFIG_FILE"; then
-              echo "DEBUG_MODE is already disabled."
-          else
-              sed -i '' 's/DEBUG_MODE="true"/DEBUG_MODE="false"/' "$WPDOCKER_CONFIG_FILE"
-              echo "DEBUG_MODE has been disabled."
-          fi
-          ;;
-      *)
-          echo "Error: Invalid action '${args[action]}'. Use 'enable' or 'disable'."
-          exit 1
-          ;;
+  enable)
+      if grep -q 'DEBUG_MODE="true"' "$WPDOCKER_CONFIG_FILE"; then
+          echo "DEBUG_MODE is already enabled."
+      else
+          sedi 's/DEBUG_MODE="false"/DEBUG_MODE="true"/' "$WPDOCKER_CONFIG_FILE"
+          echo "DEBUG_MODE has been enabled."
+      fi
+      ;;
+  disable)
+      if grep -q 'DEBUG_MODE="false"' "$WPDOCKER_CONFIG_FILE"; then
+          echo "DEBUG_MODE is already disabled."
+      else
+          sedi 's/DEBUG_MODE="true"/DEBUG_MODE="false"/' "$WPDOCKER_CONFIG_FILE"
+          echo "DEBUG_MODE has been disabled."
+      fi
+      ;;
+  *)
+      echo "Error: Invalid action '${args[action]}'. Use 'enable' or 'disable'."
+      exit 1
+      ;;
   esac
+
 }
 
 # :command.function
